//! Local error type.
//!
//! Replaces `daruma_shared::CoreError` so the skeleton is
//! dependency-free. the host maps [`PlanningError`] onto its own error surface
//! when wiring the layer. The shape is generated by layer-kit's shared
//! `layer_error!` macro instead of hand-copied per layer.

use crate::ai::AiError;

layer_kit::layer_error!(PlanningError {
    Ai(ai, "AI provider failed or returned an unusable response."),
    Serde(serde, "(De)serialization failure."),
    Validation(validation, "Output failed validation (missing or invalid fields)."),
});

impl From<AiError> for PlanningError {
    fn from(e: AiError) -> Self {
        Self::Ai(e.to_string())
    }
}
